---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: site/content/blog
  label: Articulo
  create: all
  match: "**/*"
- type: directory
  path: site/content/proyectos
  label: Proyectos
  create: all
  match: "**/*"
- type: directory
  path: site/content
  label: Paginas
  create: all
  match: "*"
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.48'
