---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: site/content/blog
  label: Articulo
  create: all
  match: "**/*"
- type: directory
  path: site/content/proyectos
  label: Proyectos
  create: all
  match: "**/*"
- type: directory
  path: site/content
  label: Paginas
  create: all
  match: "*"
upload_dir: site/static/img
public_path: "/uploads"
front_matter_path: "/src/js/cms-preview-templates"
use_front_matter_path: true
file_template: ":filename:"
version: '0.48'
