baseURL = "/"
languageCode = "es-es"
title = "Barnes & Boveri"

[taxonomies]
  category = "categories"
  tag = "tags"


[menu]


  [[menu.header]]
    weight = 2
    name = "Estructuras civiles"
    url = "#estructuras"
  [[menu.header]]
    weight = 3
    name = "Bussiness & Corporate"
    url = "#business"
  [[menu.header]]
    weight = 4
    name = "Sobre Nosotros"
    url = "#about-us"
  [[menu.header]]
    weight = 5
    name = "Proyectos"
    url = "#portfolio"
  [[menu.header]]
    weight = 6
    name = "Contacto"
    url = "#contact"


  [[menu.footer]]
    weight = 2
    name = "Estructuras civiles"
    url = "#estructuras"
  [[menu.footer]]
    weight = 3
    name = "Bussiness & Corporate"
    url = "#business"
  [[menu.footer]]
    weight = 4
    name = "Sobre Nosotros"
    url = "#about-us"
  [[menu.footer]]
    weight = 5
    name = "Proyectos"
    url = "#portfolio"
  [[menu.footer]]
    weight = 6
    name = "Contacto"
    url = "#contact"
